### ISSUE TITLE
We need a team name!

### ISSUE THREAD

**Issue by AVTpepper** [AVTpepper/gift-exchange#28]
creative, fun, christmasy, techy team name anyone?

**Comment by KaiLangen96** [comment]
What about "CodeElves Exchange"? Created it with a fast GPT promt.

**Comment by MuzhdaN** [comment]
code elves is better, or Jingle Bytes

**Comment by EbyChacko** [comment]
Jingle Hackers, Code Elves

**Comment by jeffdruid** [comment]
Code Elves
